import React from "react";
import { Route, Switch } from "react-router-dom";
import "material-design-icons-iconfont/dist/material-design-icons.css";
import Icon from "@material-ui/core/Icon";
import { makeStyles } from "@material-ui/core/styles";
import "emoji-mart/css/emoji-mart.css";
import { Emoji } from "emoji-mart";

const emojiData = [
  ":grinning:",
  ":smiley:",
  ":smile:",
  ":grin:",
  ":laughing:",
  ":sweat_smile:",
  ":joy:",
  ":rofl:",
  ":relaxed:",
  ":blush:",
  ":innocent:",
  ":slight_smile:",
  ":upside_down:",
  ":wink:",
  ":relieved:",
  ":heart_eyes:",
  ":kissing_heart:",
  ":kissing:",
  ":kissing_smiling_eyes:",
  ":kissing_closed_eyes:",
  ":yum:",
  ":stuck_out_tongue_winking_eye:",
  ":stuck_out_tongue_closed_eyes:",
  ":stuck_out_tongue:",
  ":money_mouth:",
  ":hugging:",
  ":nerd:",
  ":sunglasses:",
  ":clown:",
  ":cowboy:",
  ":smirk:",
  ":unamused:",
  ":disappointed:",
  ":pensive:",
  ":worried:",
  ":confused:",
  ":slight_frown:",
  ":frowning2:",
  ":persevere:",
  ":confounded:",
  ":tired_face:",
  ":weary:",
  ":triumph:",
  ":angry:",
  ":rage:",
  ":no_mouth:",
  ":neutral_face:",
  ":expressionless:",
  ":hushed:",
  ":frowning:",
  ":anguished:",
  ":open_mouth:",
  ":astonished:",
  ":dizzy_face:",
  ":flushed:",
  ":scream:",
  ":fearful:",
  ":cold_sweat:",
  ":cry:",
  ":disappointed_relieved:",
  ":drooling_face:",
  ":sob:",
  ":sweat:",
  ":sleepy:",
  ":sleeping:",
  ":rolling_eyes:",
  ":thinking:",
  ":lying_face:",
  ":grimacing:",
  ":zipper_mouth:",
  ":nauseated_face:",
  ":sneezing_face:",
  ":mask:",
  ":thermometer_face:",
  ":head_bandage:",
  ":smiling_imp:",
  ":imp:",
  ":japanese_ogre:",
  ":japanese_goblin:",
  ":poop:",
  ":ghost:",
  ":skull:",
  ":skull_crossbones:",
  ":alien:",
  ":space_invader:",
  ":robot:",
  ":jack_o_lantern:",
  ":smiley_cat:",
  ":smile_cat:",
  ":joy_cat:",
  ":heart_eyes_cat:",
  ":smirk_cat:",
  ":kissing_cat:",
  ":scream_cat:",
  ":crying_cat_face:",
  ":pouting_cat:",
  ":open_hands:",
  ":open_hands_tone1:",
  ":open_hands_tone2:",
  ":open_hands_tone3:",
  ":open_hands_tone4:",
  ":open_hands_tone5:",
  ":raised_hands:",
  ":raised_hands_tone1:",
  ":raised_hands_tone2:",
  ":raised_hands_tone3:",
  ":raised_hands_tone4:",
  ":raised_hands_tone5:",
  ":clap:",
  ":clap_tone1:",
  ":clap_tone2:",
  ":clap_tone3:",
  ":clap_tone4:",
  ":clap_tone5:",
  ":pray:",
  ":pray_tone1:",
  ":pray_tone2:",
  ":pray_tone3:",
  ":pray_tone4:",
  ":pray_tone5:",
  ":handshake:",
  ":thumbsup:",
  ":thumbsup_tone1:",
  ":thumbsup_tone2:",
  ":thumbsup_tone3:",
  ":thumbsup_tone4:",
  ":thumbsup_tone5:",
  ":thumbsdown:",
  ":thumbsdown_tone1:",
  ":thumbsdown_tone2:",
  ":thumbsdown_tone3:",
  ":thumbsdown_tone4:",
  ":thumbsdown_tone5:",
  ":punch:",
  ":punch_tone1:",
  ":punch_tone2:",
  ":punch_tone3:",
  ":punch_tone4:",
  ":punch_tone5:",
  ":fist:",
  ":fist_tone1:",
  ":fist_tone2:",
  ":fist_tone3:",
  ":fist_tone4:",
  ":fist_tone5:",
  ":left_facing_fist:",
  ":left_facing_fist_tone1:",
  ":left_facing_fist_tone2:",
  ":left_facing_fist_tone3:",
  ":left_facing_fist_tone4:",
  ":left_facing_fist_tone5:",
  ":right_facing_fist:",
  ":right_facing_fist_tone1:",
  ":right_facing_fist_tone2:",
  ":right_facing_fist_tone3:",
  ":right_facing_fist_tone4:",
  ":right_facing_fist_tone5:",
  ":fingers_crossed:",
  ":fingers_crossed_tone1:",
  ":fingers_crossed_tone2:",
  ":fingers_crossed_tone3:",
  ":fingers_crossed_tone4:",
  ":fingers_crossed_tone5:",
  ":v:",
  ":v_tone1:",
  ":v_tone2:",
  ":v_tone3:",
  ":v_tone4:",
  ":v_tone5:",
  ":metal:",
  ":metal_tone1:",
  ":metal_tone2:",
  ":metal_tone3:",
  ":metal_tone4:",
  ":metal_tone5:",
  ":ok_hand:",
  ":ok_hand_tone1:",
  ":ok_hand_tone2:",
  ":ok_hand_tone3:",
  ":ok_hand_tone4:",
  ":ok_hand_tone5:",
  ":point_left:",
  ":point_left_tone1:",
  ":point_left_tone2:",
  ":point_left_tone3:",
  ":point_left_tone4:",
  ":point_left_tone5:",
  ":point_right:",
  ":point_right_tone1:",
  ":point_right_tone2:",
  ":point_right_tone3:",
  ":point_right_tone4:",
  ":point_right_tone5:",
  ":point_up_2:",
  ":point_up_2_tone1:",
  ":point_up_2_tone2:",
  ":point_up_2_tone3:",
  ":point_up_2_tone4:",
  ":point_up_2_tone5:",
  ":point_down:",
  ":point_down_tone1:",
  ":point_down_tone2:",
  ":point_down_tone3:",
  ":point_down_tone4:",
  ":point_down_tone5:",
  ":point_up:",
  ":point_up_tone1:",
  ":point_up_tone2:",
  ":point_up_tone3:",
  ":point_up_tone4:",
  ":point_up_tone5:",
  ":raised_hand:",
  ":raised_hand_tone1:",
  ":raised_hand_tone2:",
  ":raised_hand_tone3:",
  ":raised_hand_tone4:",
  ":raised_hand_tone5:",
  ":raised_back_of_hand:",
  ":raised_back_of_hand_tone1:",
  ":raised_back_of_hand_tone2:",
  ":raised_back_of_hand_tone3:",
  ":raised_back_of_hand_tone4:",
  ":raised_back_of_hand_tone5:",
  ":hand_splayed:",
  ":hand_splayed_tone1:",
  ":hand_splayed_tone2:",
  ":hand_splayed_tone3:",
  ":hand_splayed_tone4:",
  ":hand_splayed_tone5:",
  ":vulcan:",
  ":vulcan_tone1:",
  ":vulcan_tone2:",
  ":vulcan_tone3:",
  ":vulcan_tone4:",
  ":vulcan_tone5:",
  ":wave:",
  ":wave_tone1:",
  ":wave_tone2:",
  ":wave_tone3:",
  ":wave_tone4:",
  ":wave_tone5:",
  ":call_me:",
  ":call_me_tone1:",
  ":call_me_tone2:",
  ":call_me_tone3:",
  ":call_me_tone4:",
  ":call_me_tone5:",
  ":muscle:",
  ":muscle_tone1:",
  ":muscle_tone2:",
  ":muscle_tone3:",
  ":muscle_tone4:",
  ":muscle_tone5:",
  ":middle_finger:",
  ":middle_finger_tone1:",
  ":middle_finger_tone2:",
  ":middle_finger_tone3:",
  ":middle_finger_tone4:",
  ":middle_finger_tone5:",
  ":writing_hand:",
  ":writing_hand_tone1:",
  ":writing_hand_tone2:",
  ":writing_hand_tone3:",
  ":writing_hand_tone4:",
  ":writing_hand_tone5:",
  ":selfie:",
  ":selfie_tone1:",
  ":selfie_tone2:",
  ":selfie_tone3:",
  ":selfie_tone4:",
  ":selfie_tone5:",
  ":nail_care:",
  ":nail_care_tone1:",
  ":nail_care_tone2:",
  ":nail_care_tone3:",
  ":nail_care_tone4:",
  ":nail_care_tone5:",
  ":ring:",
  ":lipstick:",
  ":kiss:",
  ":lips:",
  ":tongue:",
  ":ear:",
  ":ear_tone1:",
  ":ear_tone2:",
  ":ear_tone3:",
  ":ear_tone4:",
  ":ear_tone5:",
  ":nose:",
  ":nose_tone1:",
  ":nose_tone2:",
  ":nose_tone3:",
  ":nose_tone4:",
  ":nose_tone5:",
  ":footprints:",
  ":eye:",
  ":eyes:",
  ":speaking_head:",
  ":bust_in_silhouette:",
  ":busts_in_silhouette:",
  ":baby:",
  ":baby_tone1:",
  ":baby_tone2:",
  ":baby_tone3:",
  ":baby_tone4:",
  ":baby_tone5:",
  ":boy:",
  ":boy_tone1:",
  ":boy_tone2:",
  ":boy_tone3:",
  ":boy_tone4:",
  ":boy_tone5:",
  ":girl:",
  ":girl_tone1:",
  ":girl_tone2:",
  ":girl_tone3:",
  ":girl_tone4:",
  ":girl_tone5:",
  ":man:",
  ":man_tone1:",
  ":man_tone2:",
  ":man_tone3:",
  ":man_tone4:",
  ":man_tone5:",
  ":woman:",
  ":woman_tone1:",
  ":woman_tone2:",
  ":woman_tone3:",
  ":woman_tone4:",
  ":woman_tone5:",
  ":blond-haired_woman:",
  ":blond-haired_woman_tone1:",
  ":blond-haired_woman_tone2:",
  ":blond-haired_woman_tone3:",
  ":blond-haired_woman_tone4:",
  ":blond-haired_woman_tone5:",
  ":blond_haired_person:",
  ":blond_haired_person_tone1:",
  ":blond_haired_person_tone2:",
  ":blond_haired_person_tone3:",
  ":blond_haired_person_tone4:",
  ":blond_haired_person_tone5:",
  ":blond-haired_man:",
  ":blond-haired_man_tone5:",
  ":blond-haired_man_tone4:",
  ":blond-haired_man_tone3:",
  ":blond-haired_man_tone2:",
  ":blond-haired_man_tone1:",
  ":older_man:",
  ":older_man_tone1:",
  ":older_man_tone2:",
  ":older_man_tone3:",
  ":older_man_tone4:",
  ":older_man_tone5:",
  ":older_woman:",
  ":older_woman_tone1:",
  ":older_woman_tone2:",
  ":older_woman_tone3:",
  ":older_woman_tone4:",
  ":older_woman_tone5:",
  ":man_with_chinese_cap:",
  ":man_with_chinese_cap_tone1:",
  ":man_with_chinese_cap_tone2:",
  ":man_with_chinese_cap_tone3:",
  ":man_with_chinese_cap_tone4:",
  ":man_with_chinese_cap_tone5:",
  ":woman_wearing_turban:",
  ":woman_wearing_turban_tone1:",
  ":woman_wearing_turban_tone2:",
  ":woman_wearing_turban_tone3:",
  ":woman_wearing_turban_tone4:",
  ":woman_wearing_turban_tone5:",
  ":person_wearing_turban:",
  ":person_wearing_turban_tone1:",
  ":person_wearing_turban_tone2:",
  ":person_wearing_turban_tone3:",
  ":person_wearing_turban_tone4:",
  ":person_wearing_turban_tone5:",
  ":man_wearing_turban:",
  ":man_wearing_turban_tone5:",
  ":man_wearing_turban_tone4:",
  ":man_wearing_turban_tone3:",
  ":man_wearing_turban_tone2:",
  ":man_wearing_turban_tone1:",
  ":woman_police_officer:",
  ":woman_police_officer_tone1:",
  ":woman_police_officer_tone2:",
  ":woman_police_officer_tone3:",
  ":woman_police_officer_tone4:",
  ":woman_police_officer_tone5:",
  ":police_officer:",
  ":police_officer_tone1:",
  ":police_officer_tone2:",
  ":police_officer_tone3:",
  ":police_officer_tone4:",
  ":police_officer_tone5:",
  ":man_police_officer:",
  ":man_police_officer_tone5:",
  ":man_police_officer_tone4:",
  ":man_police_officer_tone3:",
  ":man_police_officer_tone2:",
  ":man_police_officer_tone1:",
  ":woman_construction_worker:",
  ":woman_construction_worker_tone1:",
  ":woman_construction_worker_tone2:",
  ":woman_construction_worker_tone3:",
  ":woman_construction_worker_tone4:",
  ":woman_construction_worker_tone5:",
  ":construction_worker:",
  ":construction_worker_tone1:",
  ":construction_worker_tone2:",
  ":construction_worker_tone3:",
  ":construction_worker_tone4:",
  ":construction_worker_tone5:",
  ":man_construction_worker:",
  ":man_construction_worker_tone5:",
  ":man_construction_worker_tone4:",
  ":man_construction_worker_tone3:",
  ":man_construction_worker_tone2:",
  ":man_construction_worker_tone1:",
  ":woman_guard:",
  ":woman_guard_tone1:",
  ":woman_guard_tone2:",
  ":woman_guard_tone3:",
  ":woman_guard_tone4:",
  ":woman_guard_tone5:",
  ":guard:",
  ":guard_tone1:",
  ":guard_tone2:",
  ":guard_tone3:",
  ":guard_tone4:",
  ":guard_tone5:",
  ":man_guard:",
  ":man_guard_tone5:",
  ":man_guard_tone4:",
  ":man_guard_tone3:",
  ":man_guard_tone2:",
  ":man_guard_tone1:",
  ":woman_detective:",
  ":woman_detective_tone1:",
  ":woman_detective_tone2:",
  ":woman_detective_tone3:",
  ":woman_detective_tone4:",
  ":woman_detective_tone5:",
  ":detective:",
  ":detective_tone1:",
  ":detective_tone2:",
  ":detective_tone3:",
  ":detective_tone4:",
  ":detective_tone5:",
  ":man_detective:",
  ":man_detective_tone5:",
  ":man_detective_tone4:",
  ":man_detective_tone3:",
  ":man_detective_tone2:",
  ":man_detective_tone1:",
  ":woman_health_worker:",
  ":woman_health_worker_tone1:",
  ":woman_health_worker_tone2:",
  ":woman_health_worker_tone3:",
  ":woman_health_worker_tone4:",
  ":woman_health_worker_tone5:",
  ":man_health_worker:",
  ":man_health_worker_tone1:",
  ":man_health_worker_tone2:",
  ":man_health_worker_tone3:",
  ":man_health_worker_tone4:",
  ":man_health_worker_tone5:",
  ":woman_farmer:",
  ":woman_farmer_tone1:",
  ":woman_farmer_tone2:",
  ":woman_farmer_tone3:",
  ":woman_farmer_tone4:",
  ":woman_farmer_tone5:",
  ":man_farmer:",
  ":man_farmer_tone1:",
  ":man_farmer_tone2:",
  ":man_farmer_tone3:",
  ":man_farmer_tone4:",
  ":man_farmer_tone5:",
  ":woman_cook:",
  ":woman_cook_tone1:",
  ":woman_cook_tone2:",
  ":woman_cook_tone3:",
  ":woman_cook_tone4:",
  ":woman_cook_tone5:",
  ":man_cook:",
  ":man_cook_tone1:",
  ":man_cook_tone2:",
  ":man_cook_tone3:",
  ":man_cook_tone4:",
  ":man_cook_tone5:",
  ":woman_student:",
  ":woman_student_tone1:",
  ":woman_student_tone2:",
  ":woman_student_tone3:",
  ":woman_student_tone4:",
  ":woman_student_tone5:",
  ":man_student:",
  ":man_student_tone1:",
  ":man_student_tone2:",
  ":man_student_tone3:",
  ":man_student_tone4:",
  ":man_student_tone5:",
  ":woman_singer:",
  ":woman_singer_tone1:",
  ":woman_singer_tone2:",
  ":woman_singer_tone3:",
  ":woman_singer_tone4:",
  ":woman_singer_tone5:",
  ":man_singer:",
  ":man_singer_tone1:",
  ":man_singer_tone2:",
  ":man_singer_tone3:",
  ":man_singer_tone4:",
  ":man_singer_tone5:",
  ":woman_teacher:",
  ":woman_teacher_tone1:",
  ":woman_teacher_tone2:",
  ":woman_teacher_tone3:",
  ":woman_teacher_tone4:",
  ":woman_teacher_tone5:",
  ":man_teacher:",
  ":man_teacher_tone1:",
  ":man_teacher_tone2:",
  ":man_teacher_tone3:",
  ":man_teacher_tone4:",
  ":man_teacher_tone5:",
  ":woman_factory_worker:",
  ":woman_factory_worker_tone1:",
  ":woman_factory_worker_tone2:",
  ":woman_factory_worker_tone3:",
  ":woman_factory_worker_tone4:",
  ":woman_factory_worker_tone5:",
  ":man_factory_worker:",
  ":man_factory_worker_tone1:",
  ":man_factory_worker_tone2:",
  ":man_factory_worker_tone3:",
  ":man_factory_worker_tone4:",
  ":man_factory_worker_tone5:",
  ":woman_technologist:",
  ":woman_technologist_tone1:",
  ":woman_technologist_tone2:",
  ":woman_technologist_tone3:",
  ":woman_technologist_tone4:",
  ":woman_technologist_tone5:",
  ":man_technologist:",
  ":man_technologist_tone1:",
  ":man_technologist_tone2:",
  ":man_technologist_tone3:",
  ":man_technologist_tone4:",
  ":man_technologist_tone5:",
  ":woman_office_worker:",
  ":woman_office_worker_tone1:",
  ":woman_office_worker_tone2:",
  ":woman_office_worker_tone3:",
  ":woman_office_worker_tone4:",
  ":woman_office_worker_tone5:",
  ":man_office_worker:",
  ":man_office_worker_tone1:",
  ":man_office_worker_tone2:",
  ":man_office_worker_tone3:",
  ":man_office_worker_tone4:",
  ":man_office_worker_tone5:",
  ":woman_mechanic:",
  ":woman_mechanic_tone1:",
  ":woman_mechanic_tone2:",
  ":woman_mechanic_tone3:",
  ":woman_mechanic_tone4:",
  ":woman_mechanic_tone5:",
  ":man_mechanic:",
  ":man_mechanic_tone1:",
  ":man_mechanic_tone2:",
  ":man_mechanic_tone3:",
  ":man_mechanic_tone4:",
  ":man_mechanic_tone5:",
  ":woman_scientist:",
  ":woman_scientist_tone1:",
  ":woman_scientist_tone2:",
  ":woman_scientist_tone3:",
  ":woman_scientist_tone4:",
  ":woman_scientist_tone5:",
  ":man_scientist:",
  ":man_scientist_tone1:",
  ":man_scientist_tone2:",
  ":man_scientist_tone3:",
  ":man_scientist_tone4:",
  ":man_scientist_tone5:",
  ":woman_artist:",
  ":woman_artist_tone1:",
  ":woman_artist_tone2:",
  ":woman_artist_tone3:",
  ":woman_artist_tone4:",
  ":woman_artist_tone5:",
  ":man_artist:",
  ":man_artist_tone1:",
  ":man_artist_tone2:",
  ":man_artist_tone3:",
  ":man_artist_tone4:",
  ":man_artist_tone5:",
  ":woman_firefighter:",
  ":woman_firefighter_tone1:",
  ":woman_firefighter_tone2:",
  ":woman_firefighter_tone3:",
  ":woman_firefighter_tone4:",
  ":woman_firefighter_tone5:",
  ":man_firefighter:",
  ":man_firefighter_tone1:",
  ":man_firefighter_tone2:",
  ":man_firefighter_tone3:",
  ":man_firefighter_tone4:",
  ":man_firefighter_tone5:",
  ":woman_pilot:",
  ":woman_pilot_tone1:",
  ":woman_pilot_tone2:",
  ":woman_pilot_tone3:",
  ":woman_pilot_tone4:",
  ":woman_pilot_tone5:",
  ":man_pilot:",
  ":man_pilot_tone1:",
  ":man_pilot_tone2:",
  ":man_pilot_tone3:",
  ":man_pilot_tone4:",
  ":man_pilot_tone5:",
  ":woman_astronaut:",
  ":woman_astronaut_tone1:",
  ":woman_astronaut_tone2:",
  ":woman_astronaut_tone3:",
  ":woman_astronaut_tone4:",
  ":woman_astronaut_tone5:",
  ":man_astronaut:",
  ":man_astronaut_tone1:",
  ":man_astronaut_tone2:",
  ":man_astronaut_tone3:",
  ":man_astronaut_tone4:",
  ":man_astronaut_tone5:",
  ":woman_judge:",
  ":woman_judge_tone1:",
  ":woman_judge_tone2:",
  ":woman_judge_tone3:",
  ":woman_judge_tone4:",
  ":woman_judge_tone5:",
  ":man_judge:",
  ":man_judge_tone1:",
  ":man_judge_tone2:",
  ":man_judge_tone3:",
  ":man_judge_tone4:",
  ":man_judge_tone5:",
  ":mrs_claus:",
  ":mrs_claus_tone1:",
  ":mrs_claus_tone2:",
  ":mrs_claus_tone3:",
  ":mrs_claus_tone4:",
  ":mrs_claus_tone5:",
  ":santa:",
  ":santa_tone1:",
  ":santa_tone2:",
  ":santa_tone3:",
  ":santa_tone4:",
  ":santa_tone5:",
  ":princess:",
  ":princess_tone1:",
  ":princess_tone2:",
  ":princess_tone3:",
  ":princess_tone4:",
  ":princess_tone5:",
  ":prince:",
  ":prince_tone1:",
  ":prince_tone2:",
  ":prince_tone3:",
  ":prince_tone4:",
  ":prince_tone5:",
  ":bride_with_veil:",
  ":bride_with_veil_tone1:",
  ":bride_with_veil_tone2:",
  ":bride_with_veil_tone3:",
  ":bride_with_veil_tone4:",
  ":bride_with_veil_tone5:",
  ":man_in_tuxedo:",
  ":man_in_tuxedo_tone1:",
  ":man_in_tuxedo_tone2:",
  ":man_in_tuxedo_tone3:",
  ":man_in_tuxedo_tone4:",
  ":man_in_tuxedo_tone5:",
  ":angel:",
  ":angel_tone1:",
  ":angel_tone2:",
  ":angel_tone3:",
  ":angel_tone4:",
  ":angel_tone5:",
  ":pregnant_woman:",
  ":pregnant_woman_tone1:",
  ":pregnant_woman_tone2:",
  ":pregnant_woman_tone3:",
  ":pregnant_woman_tone4:",
  ":pregnant_woman_tone5:",
  ":woman_bowing:",
  ":woman_bowing_tone1:",
  ":woman_bowing_tone2:",
  ":woman_bowing_tone3:",
  ":woman_bowing_tone4:",
  ":woman_bowing_tone5:",
  ":person_bowing:",
  ":person_bowing_tone1:",
  ":person_bowing_tone2:",
  ":person_bowing_tone3:",
  ":person_bowing_tone4:",
  ":person_bowing_tone5:",
  ":man_bowing:",
  ":man_bowing_tone5:",
  ":man_bowing_tone4:",
  ":man_bowing_tone3:",
  ":man_bowing_tone2:",
  ":man_bowing_tone1:",
  ":person_tipping_hand:",
  ":person_tipping_hand_tone1:",
  ":person_tipping_hand_tone2:",
  ":person_tipping_hand_tone3:",
  ":person_tipping_hand_tone4:",
  ":person_tipping_hand_tone5:",
  ":man_tipping_hand:",
  ":man_tipping_hand_tone1:",
  ":man_tipping_hand_tone2:",
  ":man_tipping_hand_tone3:",
  ":man_tipping_hand_tone4:",
  ":man_tipping_hand_tone5:",
  ":woman_tipping_hand:",
  ":woman_tipping_hand_tone5:",
  ":woman_tipping_hand_tone4:",
  ":woman_tipping_hand_tone3:",
  ":woman_tipping_hand_tone2:",
  ":woman_tipping_hand_tone1:",
  ":person_gesturing_no:",
  ":person_gesturing_no_tone1:",
  ":person_gesturing_no_tone2:",
  ":person_gesturing_no_tone3:",
  ":person_gesturing_no_tone4:",
  ":person_gesturing_no_tone5:",
  ":man_gesturing_no:",
  ":man_gesturing_no_tone1:",
  ":man_gesturing_no_tone2:",
  ":man_gesturing_no_tone3:",
  ":man_gesturing_no_tone4:",
  ":man_gesturing_no_tone5:",
  ":woman_gesturing_no:",
  ":woman_gesturing_no_tone5:",
  ":woman_gesturing_no_tone4:",
  ":woman_gesturing_no_tone3:",
  ":woman_gesturing_no_tone2:",
  ":woman_gesturing_no_tone1:",
  ":person_gesturing_ok:",
  ":person_gesturing_ok_tone1:",
  ":person_gesturing_ok_tone2:",
  ":person_gesturing_ok_tone3:",
  ":person_gesturing_ok_tone4:",
  ":person_gesturing_ok_tone5:",
  ":man_gesturing_ok:",
  ":man_gesturing_ok_tone1:",
  ":man_gesturing_ok_tone2:",
  ":man_gesturing_ok_tone3:",
  ":man_gesturing_ok_tone4:",
  ":man_gesturing_ok_tone5:",
  ":woman_gesturing_ok:",
  ":woman_gesturing_ok_tone5:",
  ":woman_gesturing_ok_tone4:",
  ":woman_gesturing_ok_tone3:",
  ":woman_gesturing_ok_tone2:",
  ":woman_gesturing_ok_tone1:",
  ":person_raising_hand:",
  ":person_raising_hand_tone1:",
  ":person_raising_hand_tone2:",
  ":person_raising_hand_tone3:",
  ":person_raising_hand_tone4:",
  ":person_raising_hand_tone5:",
  ":man_raising_hand:",
  ":man_raising_hand_tone1:",
  ":man_raising_hand_tone2:",
  ":man_raising_hand_tone3:",
  ":man_raising_hand_tone4:",
  ":man_raising_hand_tone5:",
  ":woman_raising_hand:",
  ":woman_raising_hand_tone5:",
  ":woman_raising_hand_tone4:",
  ":woman_raising_hand_tone3:",
  ":woman_raising_hand_tone2:",
  ":woman_raising_hand_tone1:",
  ":woman_facepalming:",
  ":woman_facepalming_tone1:",
  ":woman_facepalming_tone2:",
  ":woman_facepalming_tone3:",
  ":woman_facepalming_tone4:",
  ":woman_facepalming_tone5:",
  ":man_facepalming:",
  ":man_facepalming_tone1:",
  ":man_facepalming_tone2:",
  ":man_facepalming_tone3:",
  ":man_facepalming_tone4:",
  ":man_facepalming_tone5:",
  ":person_facepalming:",
  ":person_facepalming_tone1:",
  ":person_facepalming_tone2:",
  ":person_facepalming_tone3:",
  ":person_facepalming_tone4:",
  ":person_facepalming_tone5:",
  ":woman_shrugging:",
  ":woman_shrugging_tone1:",
  ":woman_shrugging_tone2:",
  ":woman_shrugging_tone3:",
  ":woman_shrugging_tone4:",
  ":woman_shrugging_tone5:",
  ":man_shrugging:",
  ":man_shrugging_tone1:",
  ":man_shrugging_tone2:",
  ":man_shrugging_tone3:",
  ":man_shrugging_tone4:",
  ":man_shrugging_tone5:",
  ":person_shrugging:",
  ":person_shrugging_tone1:",
  ":person_shrugging_tone2:",
  ":person_shrugging_tone3:",
  ":person_shrugging_tone4:",
  ":person_shrugging_tone5:",
  ":person_pouting:",
  ":person_pouting_tone1:",
  ":person_pouting_tone2:",
  ":person_pouting_tone3:",
  ":person_pouting_tone4:",
  ":person_pouting_tone5:",
  ":man_pouting:",
  ":man_pouting_tone1:",
  ":man_pouting_tone2:",
  ":man_pouting_tone3:",
  ":man_pouting_tone4:",
  ":man_pouting_tone5:",
  ":woman_pouting:",
  ":woman_pouting_tone5:",
  ":woman_pouting_tone4:",
  ":woman_pouting_tone3:",
  ":woman_pouting_tone2:",
  ":woman_pouting_tone1:",
  ":person_frowning:",
  ":person_frowning_tone1:",
  ":person_frowning_tone2:",
  ":person_frowning_tone3:",
  ":person_frowning_tone4:",
  ":person_frowning_tone5:",
  ":man_frowning:",
  ":man_frowning_tone1:",
  ":man_frowning_tone2:",
  ":man_frowning_tone3:",
  ":man_frowning_tone4:",
  ":man_frowning_tone5:",
  ":woman_frowning:",
  ":woman_frowning_tone5:",
  ":woman_frowning_tone4:",
  ":woman_frowning_tone3:",
  ":woman_frowning_tone2:",
  ":woman_frowning_tone1:",
  ":person_getting_haircut:",
  ":person_getting_haircut_tone1:",
  ":person_getting_haircut_tone2:",
  ":person_getting_haircut_tone3:",
  ":person_getting_haircut_tone4:",
  ":person_getting_haircut_tone5:",
  ":man_getting_haircut:",
  ":man_getting_haircut_tone1:",
  ":man_getting_haircut_tone2:",
  ":man_getting_haircut_tone3:",
  ":man_getting_haircut_tone4:",
  ":man_getting_haircut_tone5:",
  ":woman_getting_haircut:",
  ":woman_getting_haircut_tone5:",
  ":woman_getting_haircut_tone4:",
  ":woman_getting_haircut_tone3:",
  ":woman_getting_haircut_tone2:",
  ":woman_getting_haircut_tone1:",
  ":person_getting_massage:",
  ":person_getting_massage_tone1:",
  ":person_getting_massage_tone2:",
  ":person_getting_massage_tone3:",
  ":person_getting_massage_tone4:",
  ":person_getting_massage_tone5:",
  ":man_getting_face_massage:",
  ":man_getting_face_massage_tone1:",
  ":man_getting_face_massage_tone2:",
  ":man_getting_face_massage_tone3:",
  ":man_getting_face_massage_tone4:",
  ":man_getting_face_massage_tone5:",
  ":woman_getting_face_massage:",
  ":woman_getting_face_massage_tone5:",
  ":woman_getting_face_massage_tone4:",
  ":woman_getting_face_massage_tone3:",
  ":woman_getting_face_massage_tone2:",
  ":woman_getting_face_massage_tone1:",
  ":levitate:",
  ":man_in_business_suit_levitating_tone1:",
  ":man_in_business_suit_levitating_tone2:",
  ":man_in_business_suit_levitating_tone3:",
  ":man_in_business_suit_levitating_tone4:",
  ":man_in_business_suit_levitating_tone5:",
  ":dancer:",
  ":dancer_tone1:",
  ":dancer_tone2:",
  ":dancer_tone3:",
  ":dancer_tone4:",
  ":dancer_tone5:",
  ":man_dancing:",
  ":man_dancing_tone1:",
  ":man_dancing_tone2:",
  ":man_dancing_tone3:",
  ":man_dancing_tone4:",
  ":man_dancing_tone5:",
  ":people_with_bunny_ears_partying:",
  ":men_with_bunny_ears_partying:",
  ":women_with_bunny_ears_partying:",
  ":woman_walking:",
  ":woman_walking_tone1:",
  ":woman_walking_tone2:",
  ":woman_walking_tone3:",
  ":woman_walking_tone4:",
  ":woman_walking_tone5:",
  ":person_walking:",
  ":person_walking_tone1:",
  ":person_walking_tone2:",
  ":person_walking_tone3:",
  ":person_walking_tone4:",
  ":person_walking_tone5:",
  ":man_walking:",
  ":man_walking_tone5:",
  ":man_walking_tone4:",
  ":man_walking_tone3:",
  ":man_walking_tone2:",
  ":man_walking_tone1:",
  ":woman_running:",
  ":woman_running_tone1:",
  ":woman_running_tone2:",
  ":woman_running_tone3:",
  ":woman_running_tone4:",
  ":woman_running_tone5:",
  ":person_running:",
  ":person_running_tone1:",
  ":person_running_tone2:",
  ":person_running_tone3:",
  ":person_running_tone4:",
  ":person_running_tone5:",
  ":man_running:",
  ":man_running_tone5:",
  ":man_running_tone4:",
  ":man_running_tone3:",
  ":man_running_tone2:",
  ":man_running_tone1:",
  ":couple:",
  ":two_women_holding_hands:",
  ":two_men_holding_hands:",
  ":couple_with_heart:",
  ":couple_ww:",
  ":couple_mm:",
  ":couplekiss:",
  ":kiss_ww:",
  ":kiss_mm:",
  ":family:",
  ":family_mwg:",
  ":family_mwgb:",
  ":family_mwbb:",
  ":family_mwgg:",
  ":family_wwb:",
  ":family_wwg:",
  ":family_wwgb:",
  ":family_wwbb:",
  ":family_wwgg:",
  ":family_mmb:",
  ":family_mmg:",
  ":family_mmgb:",
  ":family_mmbb:",
  ":family_mmgg:",
  ":family_woman_boy:",
  ":family_woman_girl:",
  ":family_woman_girl_boy:",
  ":family_woman_boy_boy:",
  ":family_woman_girl_girl:",
  ":family_man_boy:",
  ":family_man_girl:",
  ":family_man_girl_boy:",
  ":family_man_boy_boy:",
  ":family_man_girl_girl:",
  ":womans_clothes:",
  ":shirt:",
  ":jeans:",
  ":necktie:",
  ":dress:",
  ":bikini:",
  ":kimono:",
  ":high_heel:",
  ":sandal:",
  ":boot:",
  ":mans_shoe:",
  ":athletic_shoe:",
  ":womans_hat:",
  ":tophat:",
  ":mortar_board:",
  ":crown:",
  ":helmet_with_cross:",
  ":school_satchel:",
  ":pouch:",
  ":purse:",
  ":handbag:",
  ":briefcase:",
  ":eyeglasses:",
  ":dark_sunglasses:",
  ":closed_umbrella:",
  ":umbrella2:",
  ":female_sign:",
  ":male_sign:",
  ":medical_symbol:",
  ":family_man_woman_boy:",
  ":couple_with_heart_woman_man:",
  ":kiss_woman_man:",
  ":face_with_raised_eyebrow:",
  ":star_struck:",
  ":crazy_face:",
  ":shushing_face:",
  ":face_with_symbols_over_mouth:",
  ":face_with_hand_over_mouth:",
  ":face_vomiting:",
  ":exploding_head:",
  ":face_with_monocle:",
  ":adult:",
  ":child:",
  ":older_adult:",
  ":bearded_person:",
  ":woman_with_headscarf:",
  ":brain:",
  ":billed_cap:",
  ":mage:",
  ":fairy:",
  ":vampire:",
  ":merperson:",
  ":elf:",
  ":genie:",
  ":zombie:",
  ":scarf:",
  ":gloves:",
  ":coat:",
  ":socks:",
  ":love_you_gesture:",
  ":love_you_gesture_tone1:",
  ":love_you_gesture_tone2:",
  ":love_you_gesture_tone3:",
  ":love_you_gesture_tone4:",
  ":love_you_gesture_tone5:",
  ":palms_up_together:",
  ":palms_up_together_tone1:",
  ":palms_up_together_tone2:",
  ":palms_up_together_tone3:",
  ":palms_up_together_tone4:",
  ":palms_up_together_tone5:",
  ":adult_tone1:",
  ":adult_tone2:",
  ":adult_tone3:",
  ":adult_tone4:",
  ":adult_tone5:",
  ":child_tone1:",
  ":child_tone2:",
  ":child_tone3:",
  ":child_tone4:",
  ":child_tone5:",
  ":older_adult_tone1:",
  ":older_adult_tone2:",
  ":older_adult_tone3:",
  ":older_adult_tone4:",
  ":older_adult_tone5:",
  ":bearded_person_tone1:",
  ":bearded_person_tone2:",
  ":bearded_person_tone3:",
  ":bearded_person_tone4:",
  ":bearded_person_tone5:",
  ":woman_with_headscarf_tone1:",
  ":woman_with_headscarf_tone2:",
  ":woman_with_headscarf_tone3:",
  ":woman_with_headscarf_tone4:",
  ":woman_with_headscarf_tone5:",
  ":mage_tone1:",
  ":mage_tone2:",
  ":mage_tone3:",
  ":mage_tone4:",
  ":mage_tone5:",
  ":fairy_tone1:",
  ":fairy_tone2:",
  ":fairy_tone3:",
  ":fairy_tone4:",
  ":fairy_tone5:",
  ":vampire_tone1:",
  ":vampire_tone2:",
  ":vampire_tone3:",
  ":vampire_tone4:",
  ":vampire_tone5:",
  ":merperson_tone1:",
  ":merperson_tone2:",
  ":merperson_tone3:",
  ":merperson_tone4:",
  ":merperson_tone5:",
  ":elf_tone1:",
  ":elf_tone2:",
  ":elf_tone3:",
  ":elf_tone4:",
  ":elf_tone5:",
  ":woman_mage:",
  ":man_mage:",
  ":woman_mage_tone1:",
  ":man_mage_tone1:",
  ":woman_mage_tone2:",
  ":man_mage_tone2:",
  ":woman_mage_tone3:",
  ":man_mage_tone3:",
  ":woman_mage_tone4:",
  ":man_mage_tone4:",
  ":woman_mage_tone5:",
  ":man_mage_tone5:",
  ":woman_fairy:",
  ":man_fairy:",
  ":woman_fairy_tone1:",
  ":man_fairy_tone1:",
  ":woman_fairy_tone2:",
  ":man_fairy_tone2:",
  ":woman_fairy_tone3:",
  ":man_fairy_tone3:",
  ":woman_fairy_tone4:",
  ":man_fairy_tone4:",
  ":woman_fairy_tone5:",
  ":man_fairy_tone5:",
  ":woman_vampire:",
  ":man_vampire:",
  ":woman_vampire_tone1:",
  ":man_vampire_tone1:",
  ":woman_vampire_tone2:",
  ":man_vampire_tone2:",
  ":woman_vampire_tone3:",
  ":man_vampire_tone3:",
  ":woman_vampire_tone4:",
  ":man_vampire_tone4:",
  ":woman_vampire_tone5:",
  ":man_vampire_tone5:",
  ":mermaid:",
  ":merman:",
  ":mermaid_tone1:",
  ":merman_tone1:",
  ":mermaid_tone2:",
  ":merman_tone2:",
  ":mermaid_tone3:",
  ":merman_tone3:",
  ":mermaid_tone4:",
  ":merman_tone4:",
  ":mermaid_tone5:",
  ":merman_tone5:",
  ":woman_elf:",
  ":man_elf:",
  ":woman_elf_tone1:",
  ":man_elf_tone1:",
  ":woman_elf_tone2:",
  ":man_elf_tone2:",
  ":woman_elf_tone3:",
  ":man_elf_tone3:",
  ":woman_elf_tone4:",
  ":man_elf_tone4:",
  ":woman_elf_tone5:",
  ":man_elf_tone5:",
  ":woman_genie:",
  ":man_genie:",
  ":woman_zombie:",
  ":man_zombie:",
  ":watch:",
  ":iphone:",
  ":calling:",
  ":computer:",
  ":keyboard:",
  ":desktop:",
  ":printer:",
  ":mouse_three_button:",
  ":trackball:",
  ":joystick:",
  ":compression:",
  ":minidisc:",
  ":floppy_disk:",
  ":cd:",
  ":dvd:",
  ":vhs:",
  ":camera:",
  ":camera_with_flash:",
  ":video_camera:",
  ":movie_camera:",
  ":projector:",
  ":film_frames:",
  ":telephone_receiver:",
  ":telephone:",
  ":pager:",
  ":fax:",
  ":tv:",
  ":radio:",
  ":microphone2:",
  ":level_slider:",
  ":control_knobs:",
  ":stopwatch:",
  ":timer:",
  ":alarm_clock:",
  ":clock:",
  ":hourglass:",
  ":hourglass_flowing_sand:",
  ":satellite:",
  ":battery:",
  ":electric_plug:",
  ":bulb:",
  ":flashlight:",
  ":candle:",
  ":wastebasket:",
  ":oil:",
  ":money_with_wings:",
  ":dollar:",
  ":yen:",
  ":euro:",
  ":pound:",
  ":moneybag:",
  ":credit_card:",
  ":gem:",
  ":scales:",
  ":wrench:",
  ":hammer:",
  ":hammer_pick:",
  ":tools:",
  ":pick:",
  ":nut_and_bolt:",
  ":gear:",
  ":chains:",
  ":gun:",
  ":bomb:",
  ":knife:",
  ":dagger:",
  ":crossed_swords:",
  ":shield:",
  ":smoking:",
  ":coffin:",
  ":urn:",
  ":amphora:",
  ":crystal_ball:",
  ":prayer_beads:",
  ":barber:",
  ":alembic:",
  ":telescope:",
  ":microscope:",
  ":hole:",
  ":pill:",
  ":syringe:",
  ":thermometer:",
  ":toilet:",
  ":potable_water:",
  ":shower:",
  ":bathtub:",
  ":bath:",
  ":bath_tone1:",
  ":bath_tone2:",
  ":bath_tone3:",
  ":bath_tone4:",
  ":bath_tone5:",
  ":bellhop:",
  ":key:",
  ":key2:",
  ":door:",
  ":couch:",
  ":bed:",
  ":sleeping_accommodation:",
  ":person_in_bed_tone1:",
  ":person_in_bed_tone2:",
  ":person_in_bed_tone3:",
  ":person_in_bed_tone4:",
  ":person_in_bed_tone5:",
  ":frame_photo:",
  ":shopping_bags:",
  ":shopping_cart:",
  ":gift:",
  ":balloon:",
  ":flags:",
  ":ribbon:",
  ":confetti_ball:",
  ":tada:",
  ":dolls:",
  ":izakaya_lantern:",
  ":wind_chime:",
  ":envelope:",
  ":envelope_with_arrow:",
  ":incoming_envelope:",
  ":e-mail:",
  ":love_letter:",
  ":inbox_tray:",
  ":outbox_tray:",
  ":package:",
  ":label:",
  ":mailbox_closed:",
  ":mailbox:",
  ":mailbox_with_mail:",
  ":mailbox_with_no_mail:",
  ":postbox:",
  ":postal_horn:",
  ":scroll:",
  ":page_with_curl:",
  ":page_facing_up:",
  ":bookmark_tabs:",
  ":bar_chart:",
  ":chart_with_upwards_trend:",
  ":chart_with_downwards_trend:",
  ":notepad_spiral:",
  ":calendar_spiral:",
  ":calendar:",
  ":date:",
  ":card_index:",
  ":card_box:",
  ":ballot_box:",
  ":file_cabinet:",
  ":clipboard:",
  ":file_folder:",
  ":open_file_folder:",
  ":dividers:",
  ":newspaper2:",
  ":newspaper:",
  ":notebook:",
  ":notebook_with_decorative_cover:",
  ":ledger:",
  ":closed_book:",
  ":green_book:",
  ":blue_book:",
  ":orange_book:",
  ":books:",
  ":book:",
  ":bookmark:",
  ":link:",
  ":paperclip:",
  ":paperclips:",
  ":triangular_ruler:",
  ":straight_ruler:",
  ":pushpin:",
  ":round_pushpin:",
  ":scissors:",
  ":pen_ballpoint:",
  ":pen_fountain:",
  ":black_nib:",
  ":paintbrush:",
  ":crayon:",
  ":pencil:",
  ":pencil2:",
  ":mag:",
  ":mag_right:",
  ":lock_with_ink_pen:",
  ":closed_lock_with_key:",
  ":lock:",
  ":unlock:",
  ":orange_heart:"
];
const useStyles = makeStyles({
  viewWrap: {
    display: "flex",
    flexDirection: "column",
    width: 400,
    height: 288,
    marginLeft: 22,
    marginTop: 21
    // marginBottom: 51,
    // backgroundColor: "pink"
  },
  // viewWrap: {
  //   display: "flex",

  //   // flexDirection: "column",
  //   justifyContent: "center",
  //   width: 446,
  //   height: 288
  // },
  search: {
    display: "flex",
    alignItems: "center",
    width: 400,
    height: 30,
    background: "rgba(36,40,42,1)",
    borderRadius: 2,
    border: "1px solid rgba(32,32,34,1)"
  },
  searchIcon: {
    marginLeft: 9,
    fontSize: 16,
    color: "#CACCCE"
  },
  searchInput: {
    width: 287,
    height: 20,
    fontSize: 14,
    marginLeft: 5,
    // font-family:PingFangSC-Medium,PingFang SC;
    fontWeight: 500,
    color: "rgba(118,121,122,1)",
    //去掉边框以及阴影
    background: "rgba(36,40,42,1)",
    outlineColor: "invert",
    outlineStyle: "none ",
    outlineWidth: 0,
    border: "none",
    boxShadow: "none",
    borderStyle: "none",
    textShadow: "none"
  },

  recentEmoji: {
    display: "flex",
    flexDirection: "column",
    // justifyContent: "space-between",
    width: 400,
    height: 65,
    marginTop: 23
    // backgroundColor: "blue"
  },
  emojiPackage: {
    display: "flex",
    flexDirection: "column",
    // justifyContent: "space-between",
    width: 417,
    height: 147,
    marginTop: 21
    // backgroundColor: "red"
  },
  title: {
    width: 24,
    height: 17,
    fontSize: 12,
    // font-family:PingFangSC-Medium,PingFang SC;
    fontWeight: 500,
    color: "rgba(184,186,186,1)",
    marginBottom: 9
    // backgroundColor: "red"
  },
  recentIconWrap: {
    display: "flex",
    // alignItems: "center",
    height: 30,
    marginTop: 8
    // backgroundColor: "blue"
  },
  emojiIcon: {
    display: "flex",
    alignItems: "center",
    // justifyContent: "center",
    flexShrink: 0,
    fontSize: 26,
    marginRight: 4,
    marginBottom: 7,
    height: 30,
    width: 30,
    cursor: "pointer"
    // backgroundColor: "pink"
  },
  emojiIconWrap: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    height: 120,
    overflow: "auto",
    // backgroundColor: "green",
    "&::-webkit-scrollbar": {
      width: 6
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(184,186,186,1)",
      borderRadius: 2
    }
  },
  uploadImage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 300,
    height: 30,
    marginLeft: 50,
    marginTop: 25,
    background: "rgba(0,158,202,1)",
    borderRadius: 5,
    cursor: "pointer"
    // border: "1px solid rgba(32,32,34,1)"
  },
  uploadImageFont: {
    fontSize: 14,
    fontWeight: 500,
    color: "#E7E8E8FF"
  }
});

function EmojiIcon() {
  const classes = useStyles();
  return (
    <div className={classes.viewWrap}>
      {/* <Picker
        autoFocus={true} //安装后自动聚焦搜索输入
        color={"pink"} //顶部栏锚点选择和悬停颜色
        darkMode={true} // 黑暗模式
        include={["search", "recent", "people", "foods", "activity", "symbols"]} //选择显示的表情包种类
        onSelect={e => alert(e)} //选择
        set={"apple"} //主题风格
        showPreview={false} //预览提示
        showSkinTones={false} //显示肤色选择器。禁用此功能并showPreview完全删除页脚。
        emojiTooltip={true} //未悬停表情符号时显示的标题
        notFoundEmoji={"mag"} //没有搜索结果时候显示的图片
        i18n={{
          //本地语言字符串设置(汉化)
          clear: "Clear", // Accessible label on "clear" button
          notfound: "没有找到对应表情包", //搜索检查不到时候后输出显示内容
          skintext: "Choose your default skin tone", // 默认的肤色
          search: "搜索",
          categories: {
            search: "搜索結果",
            recent: "最近",
            people: "人物",
            nature: "动物自然",
            foods: "食物",
            activity: "活动",
            places: "旅行",
            objects: "对象",
            symbols: "記号",
            flags: "标志",
            custom: "风俗"
          }
        }}
        style={{
          width: 446,
          // height: "288px",

          backgroundColor: "rgba(63,68,71,1)",
          bottom: 0
          // position: "absolute",
          // zIndex: "1"
        }}
      /> */}
      {/* ---------------原始内容---------------- */}
      <div className={classes.search}>
        <Icon className={classes.searchIcon}>search</Icon>
        <input placeholder="快速查找" className={classes.searchInput}></input>
      </div>
      <div className={classes.recentEmoji}>
        <span className={classes.title}>最近</span>
        <div className={classes.recentIconWrap}>
          <span
            className={classes.emojiIcon}
            onClick={() => {
              alert("系选择了一个emoji");
            }}
          >
            🍉
          </span>
          <span className={classes.emojiIcon}> 👽</span>
          <span className={classes.emojiIcon}> 🍓</span>
          <span className={classes.emojiIcon}> 🍟</span>
          <span className={classes.emojiIcon}> 🍔 </span>
          <span className={classes.emojiIcon}> 🍥</span>
          <span className={classes.emojiIcon}> 📲</span>
          <span className={classes.emojiIcon}> 🇨🇳</span>
          <span className={classes.emojiIcon}> 🇺🇸</span>
        </div>
      </div>
      <div className={classes.emojiPackage}>
        <span className={classes.title}>人物</span>
        <div className={classes.emojiIconWrap}>
          {emojiData.map((item, index) => (
            <span
              className={classes.emojiIcon}
              key={index}
              onClick={(emoji, event) => {
                console.log(emojiData[index]);
                console.log(event);
              }}
            >
              <Emoji emoji={item} size={28} />
            </span>
          ))}
        </div>
      </div>
      {/* ------------------原始内容----------------------------- */}
    </div>
  );
}
function UploadImage(props) {
  const { onClickUploadImage } = props;
  const classes = useStyles();
  return (
    <div className={classes.viewWrap}>
      <div className={classes.uploadImage}>
        <span className={classes.uploadImageFont} onClick={onClickUploadImage}>
          选择一个图片
        </span>
      </div>
    </div>
  );
}
function ChangeIconMenuRoute(props) {
  const { chooseImage } = props;
  const classes = useStyles();
  return (
    <div>
      <Switch>
        <Route exact path="/emoji">
          <EmojiIcon />
        </Route>
        <Route exact path="/image">
          <UploadImage onClickUploadImage={chooseImage} />
        </Route>
      </Switch>
    </div>
  );
}
export default ChangeIconMenuRoute;

{
  /* <span className={classes.emojiIcon}> 🇨🇳</span>
<span className={classes.emojiIcon}> 🇺🇸</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> ⌛️</span>
<span className={classes.emojiIcon}> 🐔 </span>
<span className={classes.emojiIcon}> 🦄</span>
<span className={classes.emojiIcon}> 🐢</span>
<span className={classes.emojiIcon}> 🐡 </span>
<span className={classes.emojiIcon}> 🐶</span>
<span className={classes.emojiIcon}> 🐹 </span>
<span className={classes.emojiIcon}> 🐰</span>
<span className={classes.emojiIcon}> 🦊</span>
<span className={classes.emojiIcon}> 😂</span>
<span className={classes.emojiIcon}> 🤖</span>
<span className={classes.emojiIcon}> 👑</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span>
<span className={classes.emojiIcon}> 👑</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🇨🇳</span>
<span className={classes.emojiIcon}> 🇺🇸</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🐰</span>
<span className={classes.emojiIcon}> 🦊</span>
<span className={classes.emojiIcon}> 😂</span>
<span className={classes.emojiIcon}> 🤖</span>
<span className={classes.emojiIcon}> 👑</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🐰</span>
<span className={classes.emojiIcon}> 🦊</span>
<span className={classes.emojiIcon}> 😂</span>
<span className={classes.emojiIcon}> 🤖</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 👑</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span>
<span className={classes.emojiIcon}> 😂</span>
<span className={classes.emojiIcon}> 🤖</span>
<span className={classes.emojiIcon}> 👑</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 🐰</span>
<span className={classes.emojiIcon}> 🦊</span>
<span className={classes.emojiIcon}> 😂</span>
<span className={classes.emojiIcon}> 🤖</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span>
<span className={classes.emojiIcon}> 🚀</span>
<span className={classes.emojiIcon}> 👑</span>
<span className={classes.emojiIcon}> 🙏🏻</span>
<span className={classes.emojiIcon}> 🍓</span>
<span className={classes.emojiIcon}> 🚌</span>
<span className={classes.emojiIcon}> 📲</span> */
}
